/** Pre-recorded voice clips under public/voices/ */

export const VOICE_LINES = {
  // Coach — female Jenny
  nice: '/voices/nice.mp3',
  solid: '/voices/solid.mp3',
  good_call: '/voices/good_call.mp3',
  that_works: '/voices/that_works.mp3',
  clean: '/voices/clean.mp3',
  too_close: '/voices/too_close.mp3',
  row_taken: '/voices/row_taken.mp3',
  region_full: '/voices/region_full.mp3',
  nope: '/voices/nope.mp3',
  nudge: '/voices/nudge.mp3',
  cleared: '/voices/cleared.mp3',
  board_complete: '/voices/board_complete.mp3',
  out_of_hearts: '/voices/out_of_hearts.mp3',
  tough_board: '/voices/tough_board.mp3',
  prize_time: '/voices/prize_time.mp3',
  new_badge: '/voices/new_badge.mp3',
  cosmic: '/voices/cosmic.mp3',
  ruins: '/voices/ruins.mp3',
  neon: '/voices/neon.mp3',
  ocean: '/voices/ocean.mp3',
  ember: '/voices/ember.mp3',
  crystal: '/voices/crystal.mp3',
  // Roman — human male BrianNeural (cheers + putdowns)
  roman_awesome: '/voices/roman_awesome.mp3',
  roman_legend: '/voices/roman_legend.mp3',
  roman_highfive: '/voices/roman_highfive.mp3',
  roman_win: '/voices/roman_win.mp3',
  roman_brain: '/voices/roman_brain.mp3',
  roman_boss: '/voices/roman_boss.mp3',
  roman_sparkle: '/voices/roman_sparkle.mp3',
  roman_proud: '/voices/roman_proud.mp3',
  roman_clutch: '/voices/roman_clutch.mp3',
  roman_smooth: '/voices/roman_smooth.mp3',
  roman_cheer: '/voices/roman_cheer.mp3',
  roman_cook: '/voices/roman_cook.mp3',
  roman_critter: '/voices/roman_critter.mp3',
  roman_stash: '/voices/roman_stash.mp3',
  roman_prize: '/voices/roman_prize.mp3',
  roman_hint: '/voices/roman_hint.mp3',
  roman_nudge: '/voices/roman_nudge.mp3',
  roman_close: '/voices/roman_close.mp3',
  roman_oops: '/voices/roman_oops.mp3',
  roman_bonk: '/voices/roman_bonk.mp3',
  roman_nope: '/voices/roman_nope.mp3',
  roman_silly: '/voices/roman_silly.mp3',
  roman_brainfart: '/voices/roman_brainfart.mp3',
  roman_retry: '/voices/roman_retry.mp3',
  roman_hearts: '/voices/roman_hearts.mp3',
  roman_colorblind: '/voices/roman_colorblind.mp3',
  roman_samecolor: '/voices/roman_samecolor.mp3',
  roman_rowmate: '/voices/roman_rowmate.mp3',
  roman_coltaken: '/voices/roman_coltaken.mp3',
  roman_cuddle: '/voices/roman_cuddle.mp3',
  roman_highhopes: '/voices/roman_highhopes.mp3',
  roman_cantwin: '/voices/roman_cantwin.mp3',
  roman_trying: '/voices/roman_trying.mp3',
  roman_stillbetter: '/voices/roman_stillbetter.mp3',
  roman_skillissue: '/voices/roman_skillissue.mp3',
  roman_warmup: '/voices/roman_warmup.mp3',
  roman_almost: '/voices/roman_almost.mp3',
  roman_sleeping: '/voices/roman_sleeping.mp3',
  roman_practice: '/voices/roman_practice.mp3',
  roman_myboard: '/voices/roman_myboard.mp3',
  roman_sandwich: '/voices/roman_sandwich.mp3',
  roman_itchy: '/voices/roman_itchy.mp3',
  roman_plotwin: '/voices/roman_plotwin.mp3',
  roman_okayfine: '/voices/roman_okayfine.mp3',
  roman_cocky: '/voices/roman_cocky.mp3',
  roman_sock: '/voices/roman_sock.mp3',
  roman_taco: '/voices/roman_taco.mp3',
  roman_juice: '/voices/roman_juice.mp3',
  roman_dino: '/voices/roman_dino.mp3',
  roman_nugget: '/voices/roman_nugget.mp3',
  roman_shoe: '/voices/roman_shoe.mp3',
  roman_potato: '/voices/roman_potato.mp3',
  roman_sneeze: '/voices/roman_sneeze.mp3',
  roman_fridge: '/voices/roman_fridge.mp3',
  roman_nap: '/voices/roman_nap.mp3',
  roman_spaghetti: '/voices/roman_spaghetti.mp3',
  roman_raccoon: '/voices/roman_raccoon.mp3',
  roman_shrug: '/voices/roman_shrug.mp3',
  roman_dance: '/voices/roman_dance.mp3',
  roman_forgot: '/voices/roman_forgot.mp3',
  roman_toes: '/voices/roman_toes.mp3',
  roman_eyeballs: '/voices/roman_eyeballs.mp3',
  roman_victoryburp: '/voices/roman_victoryburp.mp3',
  roman_highfiveself: '/voices/roman_highfiveself.mp3',
  roman_broccoli: '/voices/roman_broccoli.mp3',
  roman_pickle: '/voices/roman_pickle.mp3',
  roman_banana: '/voices/roman_banana.mp3',
  roman_cheese: '/voices/roman_cheese.mp3',
  roman_pants: '/voices/roman_pants.mp3',
  roman_booger: '/voices/roman_booger.mp3',
  roman_lizard: '/voices/roman_lizard.mp3',
  roman_ghost: '/voices/roman_ghost.mp3',
  roman_unicorn: '/voices/roman_unicorn.mp3',
  roman_worm: '/voices/roman_worm.mp3',
  roman_trumpet: '/voices/roman_trumpet.mp3',
  roman_bubblegum: '/voices/roman_bubblegum.mp3',
  roman_helicopter: '/voices/roman_helicopter.mp3',
  roman_underpants: '/voices/roman_underpants.mp3',
  roman_moonwalk: '/voices/roman_moonwalk.mp3',
  roman_idle_hello: '/voices/roman_idle_hello.mp3',
  roman_idle_century: '/voices/roman_idle_century.mp3',
  roman_idle_sandwich: '/voices/roman_idle_sandwich.mp3',
  roman_idle_blink: '/voices/roman_idle_blink.mp3',
  roman_idle_loading: '/voices/roman_idle_loading.mp3',
  roman_idle_admire: '/voices/roman_idle_admire.mp3',
  roman_idle_sphinx: '/voices/roman_idle_sphinx.mp3',
  roman_idle_snore: '/voices/roman_idle_snore.mp3',
  roman_wrong_bold: '/voices/roman_wrong_bold.mp3',
  roman_wrong_complaint: '/voices/roman_wrong_complaint.mp3',
  roman_wrong_oof: '/voices/roman_wrong_oof.mp3',
  roman_wrong_politely: '/voices/roman_wrong_politely.mp3',
  roman_wrong_grandma: '/voices/roman_wrong_grandma.mp3',
  roman_wrong_wifi: '/voices/roman_wrong_wifi.mp3',
  roman_wrong_drama: '/voices/roman_wrong_drama.mp3',
  roman_wrong_trophy: '/voices/roman_wrong_trophy.mp3',
  roman_lose_nap: '/voices/roman_lose_nap.mp3',
  roman_lose_fought: '/voices/roman_lose_fought.mp3',
  roman_lose_snacks: '/voices/roman_lose_snacks.mp3',
  roman_lose_round: '/voices/roman_lose_round.mp3',
  roman_hint_psst: '/voices/roman_hint_psst.mp3',
  roman_hint_secret: '/voices/roman_hint_secret.mp3',
  roman_hint_clue: '/voices/roman_hint_clue.mp3',
  roman_badge_shiny: '/voices/roman_badge_shiny.mp3',
  roman_badge_fridge: '/voices/roman_badge_fridge.mp3',
  roman_badge_wear: '/voices/roman_badge_wear.mp3',
  roman_badge_impressed: '/voices/roman_badge_impressed.mp3',
  roman_spin_spoken: '/voices/roman_spin_spoken.mp3',
  roman_spin_ooh: '/voices/roman_spin_ooh.mp3',
  roman_spin_lucky: '/voices/roman_spin_lucky.mp3',
  roman_stash_party: '/voices/roman_stash_party.mp3',
  roman_stash_jazz: '/voices/roman_stash_jazz.mp3',
  // Old-timer heckler (en-AU-WilliamMultilingualNeural + rasp)
  old_wrong_stick: '/voices/old_wrong_stick.mp3',
  old_wrong_pigeon: '/voices/old_wrong_pigeon.mp3',
  old_wrong_love: '/voices/old_wrong_love.mp3',
  old_wrong_choice: '/voices/old_wrong_choice.mp3',
  old_wrong_money: '/voices/old_wrong_money.mp3',
  old_wrong_tea: '/voices/old_wrong_tea.mp3',
  old_wrong_chaos: '/voices/old_wrong_chaos.mp3',
  old_wrong_knees: '/voices/old_wrong_knees.mp3',
  old_wrong_personal: '/voices/old_wrong_personal.mp3',
  old_wrong_close: '/voices/old_wrong_close.mp3',
  old_wrong_again: '/voices/old_wrong_again.mp3',
  old_wrong_refund: '/voices/old_wrong_refund.mp3',
  old_wrong_nickel: '/voices/old_wrong_nickel.mp3',
  old_wrong_teacher: '/voices/old_wrong_teacher.mp3',
  old_wrong_loudly: '/voices/old_wrong_loudly.mp3',
  old_idle_twenty: '/voices/old_idle_twenty.mp3',
  old_idle_crossword: '/voices/old_idle_crossword.mp3',
  old_idle_kettle: '/voices/old_idle_kettle.mp3',
  old_idle_nap: '/voices/old_idle_nap.mp3',
  old_idle_glacier: '/voices/old_idle_glacier.mp3',
  old_idle_younger: '/voices/old_idle_younger.mp3',
  old_idle_gossip: '/voices/old_idle_gossip.mp3',
  old_hint_stare: '/voices/old_hint_stare.mp3',
  old_hint_tell: '/voices/old_hint_tell.mp3',
  old_hint_wheels: '/voices/old_hint_wheels.mp3',
  old_hint_push: '/voices/old_hint_push.mp3',
  old_hint_smart: '/voices/old_hint_smart.mp3',
  old_undo_hokey: '/voices/old_undo_hokey.mp3',
  old_undo_dizzy: '/voices/old_undo_dizzy.mp3',
  old_undo_rocking: '/voices/old_undo_rocking.mp3',
  old_undo_vacation: '/voices/old_undo_vacation.mp3',
  old_lose_tape: '/voices/old_lose_tape.mp3',
  old_lose_goldfish: '/voices/old_lose_goldfish.mp3',
  old_lose_sideways: '/voices/old_lose_sideways.mp3',
  old_lose_popcorn: '/voices/old_lose_popcorn.mp3',
  old_win_eventually: '/voices/old_win_eventually.mp3',
  old_win_ugly: '/voices/old_win_ugly.mp3',
  roman_record_best: '/voices/roman_record_best.mp3',
  roman_record_faster: '/voices/roman_record_faster.mp3',
  roman_record_beat: '/voices/roman_record_beat.mp3',
  roman_nearmiss: '/voices/roman_nearmiss.mp3',
  roman_trial_clear: '/voices/roman_trial_clear.mp3',
  roman_daily_done: '/voices/roman_daily_done.mp3',
  old_record_head: '/voices/old_record_head.mp3',
  old_record_tea: '/voices/old_record_tea.mp3',
  old_nearmiss: '/voices/old_nearmiss.mp3',
  old_win_paint: '/voices/old_win_paint.mp3',
  old_win_yesterday: '/voices/old_win_yesterday.mp3',
  old_win_gaveup: '/voices/old_win_gaveup.mp3',
  old_rescue_modern: '/voices/old_rescue_modern.mp3',
  old_rescue_refund: '/voices/old_rescue_refund.mp3',
  old_rescue_coins: '/voices/old_rescue_coins.mp3',
  old_rescue_cat: '/voices/old_rescue_cat.mp3',
  old_aside_smell: '/voices/old_aside_smell.mp3',
  old_aside_heat: '/voices/old_aside_heat.mp3',
  old_aside_glasses: '/voices/old_aside_glasses.mp3',
  old_aside_stove: '/voices/old_aside_stove.mp3',
  old_aside_tuesday: '/voices/old_aside_tuesday.mp3',
  old_aside_tea: '/voices/old_aside_tea.mp3',
  old_aside_knees: '/voices/old_aside_knees.mp3',
  old_aside_remote: '/voices/old_aside_remote.mp3',
  old_aside_cat: '/voices/old_aside_cat.mp3',
  old_aside_socks: '/voices/old_aside_socks.mp3',
  old_jab_mitts: '/voices/old_jab_mitts.mp3',
  old_jab_bingo: '/voices/old_jab_bingo.mp3',
  old_jab_phone: '/voices/old_jab_phone.mp3',
  old_jab_backday: '/voices/old_jab_backday.mp3',
  old_jab_buddy: '/voices/old_jab_buddy.mp3',
  old_jab_square: '/voices/old_jab_square.mp3',
  old_jab_thinking: '/voices/old_jab_thinking.mp3',
  old_jab_patience: '/voices/old_jab_patience.mp3',
  old_jab_map: '/voices/old_jab_map.mp3',
  old_jab_shoes: '/voices/old_jab_shoes.mp3',
  old_good_fine: '/voices/old_good_fine.mp3',
  old_good_accident: '/voices/old_good_accident.mp3',
  old_good_tea: '/voices/old_good_tea.mp3',
  old_good_knees: '/voices/old_good_knees.mp3',
  old_good_once: '/voices/old_good_once.mp3',
  old_good_square: '/voices/old_good_square.mp3',
  old_good_grumble: '/voices/old_good_grumble.mp3',
  old_good_day: '/voices/old_good_day.mp3',
  spark_unlocked: '/voices/spark_unlocked.mp3',
  spark_1: '/voices/spark_1.mp3',
  spark_2: '/voices/spark_2.mp3',
  spark_3: '/voices/spark_3.mp3',
  spark_4: '/voices/spark_4.mp3',
  spark_have_1: '/voices/spark_have_1.mp3',
  spark_have_2: '/voices/spark_have_2.mp3',
  spark_have_3: '/voices/spark_have_3.mp3',
  spark_have_4: '/voices/spark_have_4.mp3',
  // 9.27-a: more lines for the busiest categories
  coach_hint_look: '/voices/coach_hint_look.mp3',
  coach_hint_help: '/voices/coach_hint_help.mp3',
  coach_hint_glow: '/voices/coach_hint_glow.mp3',
  coach_hint_clue: '/voices/coach_hint_clue.mp3',
  coach_hint_peek: '/voices/coach_hint_peek.mp3',
  coach_hint_step: '/voices/coach_hint_step.mp3',
  coach_hint_try: '/voices/coach_hint_try.mp3',
  coach_lose_breathe: '/voices/coach_lose_breathe.mp3',
  coach_lose_again: '/voices/coach_lose_again.mp3',
  coach_lose_next: '/voices/coach_lose_next.mp3',
  coach_prize_ooh: '/voices/coach_prize_ooh.mp3',
  coach_prize_see: '/voices/coach_prize_see.mp3',
  coach_badge_earned: '/voices/coach_badge_earned.mp3',
  coach_badge_look: '/voices/coach_badge_look.mp3',
  roman_hint_wink: '/voices/roman_hint_wink.mp3',
  roman_hint_spy: '/voices/roman_hint_spy.mp3',
  roman_hint_treasure: '/voices/roman_hint_treasure.mp3',
  roman_lose_cape: '/voices/roman_lose_cape.mp3',
  roman_lose_shake: '/voices/roman_lose_shake.mp3',
  roman_lose_pillow: '/voices/roman_lose_pillow.mp3',
  old_wrong_toaster: '/voices/old_wrong_toaster.mp3',
  old_wrong_bold: '/voices/old_wrong_bold.mp3',
  old_wrong_hallway: '/voices/old_wrong_hallway.mp3',
  old_wrong_history: '/voices/old_wrong_history.mp3',
  old_wrong_spectacles: '/voices/old_wrong_spectacles.mp3',
  old_good_clock: '/voices/old_good_clock.mp3',
  old_good_surprised: '/voices/old_good_surprised.mp3',
  old_good_lucky: '/voices/old_good_lucky.mp3',
  old_good_clap: '/voices/old_good_clap.mp3',
  old_hint_flashlight: '/voices/old_hint_flashlight.mp3',
  old_hint_grandkid: '/voices/old_hint_grandkid.mp3',
  old_hint_cane: '/voices/old_hint_cane.mp3',
  old_hint_cheating: '/voices/old_hint_cheating.mp3',
  old_undo_face: '/voices/old_undo_face.mp3',
  old_undo_yoyo: '/voices/old_undo_yoyo.mp3',
  old_undo_regret: '/voices/old_undo_regret.mp3',
  old_undo_aging: '/voices/old_undo_aging.mp3',
  old_undo_eraser: '/voices/old_undo_eraser.mp3',
  old_win_squirrel: '/voices/old_win_squirrel.mp3',
  old_win_frame: '/voices/old_win_frame.mp3',
  old_win_napped: '/voices/old_win_napped.mp3',
  old_win_twothree: '/voices/old_win_twothree.mp3',
  old_lose_called: '/voices/old_lose_called.mp3',
  old_lose_sandwich: '/voices/old_lose_sandwich.mp3',
  old_lose_nephew: '/voices/old_lose_nephew.mp3',
  old_lose_deal: '/voices/old_lose_deal.mp3',
  old_idle_mail: '/voices/old_idle_mail.mp3',
  old_idle_beard: '/voices/old_idle_beard.mp3',
  old_idle_birthday: '/voices/old_idle_birthday.mp3',
  old_aside_humming: '/voices/old_aside_humming.mp3',
  old_aside_pigeons: '/voices/old_aside_pigeons.mp3',
  old_rescue_lifeguard: '/voices/old_rescue_lifeguard.mp3',
  old_rescue_parachute: '/voices/old_rescue_parachute.mp3',
  // 9.30-g: approved voice-tip lines (all three voices) + combined not-best lines
  tip_stall_roman_clock: '/voices/tip_stall_roman_clock.mp3',
  tip_stall_roman_combo: '/voices/tip_stall_roman_combo.mp3',
  tip_stall_roman_beg: '/voices/tip_stall_roman_beg.mp3',
  tip_stall_coach_combo: '/voices/tip_stall_coach_combo.mp3',
  tip_stall_coach_marks: '/voices/tip_stall_coach_marks.mp3',
  tip_stall_coach_fewest: '/voices/tip_stall_coach_fewest.mp3',
  tip_stall_old_combo: '/voices/tip_stall_old_combo.mp3',
  tip_stall_old_timer: '/voices/tip_stall_old_timer.mp3',
  tip_stall_old_free: '/voices/tip_stall_old_free.mp3',
  tip_undo_roman_count: '/voices/tip_undo_roman_count.mp3',
  tip_undo_roman_sock: '/voices/tip_undo_roman_sock.mp3',
  tip_undo_roman_rules: '/voices/tip_undo_roman_rules.mp3',
  tip_undo_coach_cost: '/voices/tip_undo_coach_cost.mp3',
  tip_undo_coach_stars: '/voices/tip_undo_coach_stars.mp3',
  tip_undo_coach_marks: '/voices/tip_undo_coach_marks.mp3',
  tip_undo_old_prices: '/voices/tip_undo_old_prices.mp3',
  tip_undo_old_rent: '/voices/tip_undo_old_rent.mp3',
  tip_undo_old_crying: '/voices/tip_undo_old_crying.mp3',
  tip_star_roman_time: '/voices/tip_star_roman_time.mp3',
  tip_star_coach_time: '/voices/tip_star_coach_time.mp3',
  tip_star_old_time: '/voices/tip_star_old_time.mp3',
  tip_star_roman_recipe: '/voices/tip_star_roman_recipe.mp3',
  tip_star_coach_undo: '/voices/tip_star_coach_undo.mp3',
  tip_star_old_barber: '/voices/tip_star_old_barber.mp3',
  tip_star_roman_combo: '/voices/tip_star_roman_combo.mp3',
  tip_star_coach_score: '/voices/tip_star_coach_score.mp3',
  tip_star_old_coffee: '/voices/tip_star_old_coffee.mp3',
  tip_star_roman_trial: '/voices/tip_star_roman_trial.mp3',
  tip_star_coach_card: '/voices/tip_star_coach_card.mp3',
  tip_star_old_motel: '/voices/tip_star_old_motel.mp3',
  tip_stuck_roman_shiny: '/voices/tip_stuck_roman_shiny.mp3',
  tip_stuck_roman_1987: '/voices/tip_stuck_roman_1987.mp3',
  tip_stuck_roman_row: '/voices/tip_stuck_roman_row.mp3',
  tip_stuck_coach_hint: '/voices/tip_stuck_coach_hint.mp3',
  tip_stuck_coach_region: '/voices/tip_stuck_coach_region.mp3',
  tip_stuck_coach_learn: '/voices/tip_stuck_coach_learn.mp3',
  tip_stuck_old_complaint: '/voices/tip_stuck_old_complaint.mp3',
  tip_stuck_old_knees: '/voices/tip_stuck_old_knees.mp3',
  tip_stuck_old_pride: '/voices/tip_stuck_old_pride.mp3',
  tip_trial_roman_welcome: '/voices/tip_trial_roman_welcome.mp3',
  tip_trial_roman_coins: '/voices/tip_trial_roman_coins.mp3',
  tip_trial_coach_rules: '/voices/tip_trial_coach_rules.mp3',
  tip_trial_coach_marks: '/voices/tip_trial_coach_marks.mp3',
  tip_trial_old_life: '/voices/tip_trial_old_life.mp3',
  tip_trial_old_doctor: '/voices/tip_trial_old_doctor.mp3',
  tip_daily_roman_first: '/voices/tip_daily_roman_first.mp3',
  tip_daily_roman_streak: '/voices/tip_daily_roman_streak.mp3',
  tip_daily_coach_careful: '/voices/tip_daily_coach_careful.mp3',
  tip_daily_coach_streak: '/voices/tip_daily_coach_streak.mp3',
  tip_daily_old_parking: '/voices/tip_daily_old_parking.mp3',
  tip_daily_old_glasses: '/voices/tip_daily_old_glasses.mp3',
  old_notbest_tsk: '/voices/old_notbest_tsk.mp3',
  old_notbest_yesterday: '/voices/old_notbest_yesterday.mp3',
  old_notbest_rerun: '/voices/old_notbest_rerun.mp3',
  old_notbest_ghost: '/voices/old_notbest_ghost.mp3',
  old_notbest_calendar: '/voices/old_notbest_calendar.mp3',
  old_notbest_knees: '/voices/old_notbest_knees.mp3',
  old_notbest_tea: '/voices/old_notbest_tea.mp3',
  old_notbest_downhill: '/voices/old_notbest_downhill.mp3',
  old_notbest_slowpoke: '/voices/old_notbest_slowpoke.mp3',
  roman_notbest_record: '/voices/roman_notbest_record.mp3',
  roman_notbest_again: '/voices/roman_notbest_again.mp3',
  roman_notbest_turtle: '/voices/roman_notbest_turtle.mp3',
  coach_notbest_clear: '/voices/coach_notbest_clear.mp3',
  coach_notbest_close: '/voices/coach_notbest_close.mp3',
  // 9.30-i: approved thin-pool lines (record, Trial clear, Daily done, coach not-best / stash)
  roman_record_fireworks: '/voices/roman_record_fireworks.mp3',
  roman_record_clock: '/voices/roman_record_clock.mp3',
  roman_record_fridge: '/voices/roman_record_fridge.mp3',
  roman_record_zoom: '/voices/roman_record_zoom.mp3',
  roman_record_notes: '/voices/roman_record_notes.mp3',
  roman_record_socks: '/voices/roman_record_socks.mp3',
  old_record_nap: '/voices/old_record_nap.mp3',
  old_record_teeth: '/voices/old_record_teeth.mp3',
  old_record_luck: '/voices/old_record_luck.mp3',
  old_record_showoff: '/voices/old_record_showoff.mp3',
  old_record_rocking: '/voices/old_record_rocking.mp3',
  old_record_pencil: '/voices/old_record_pencil.mp3',
  coach_record_best: '/voices/coach_record_best.mp3',
  coach_record_faster: '/voices/coach_record_faster.mp3',
  coach_record_proud: '/voices/coach_record_proud.mp3',
  coach_record_practice: '/voices/coach_record_practice.mp3',
  roman_trial_shocked: '/voices/roman_trial_shocked.mp3',
  roman_trial_coins: '/voices/roman_trial_coins.mp3',
  roman_trial_unfair: '/voices/roman_trial_unfair.mp3',
  roman_trial_crown: '/voices/roman_trial_crown.mp3',
  roman_trial_harder: '/voices/roman_trial_harder.mp3',
  coach_trial_clear: '/voices/coach_trial_clear.mp3',
  coach_trial_clock: '/voices/coach_trial_clock.mp3',
  coach_trial_steady: '/voices/coach_trial_steady.mp3',
  old_trial_huh: '/voices/old_trial_huh.mp3',
  old_trial_candy: '/voices/old_trial_candy.mp3',
  old_trial_complaint: '/voices/old_trial_complaint.mp3',
  roman_daily_streak: '/voices/roman_daily_streak.mp3',
  roman_daily_cook: '/voices/roman_daily_cook.mp3',
  roman_daily_calendar: '/voices/roman_daily_calendar.mp3',
  roman_daily_snack: '/voices/roman_daily_snack.mp3',
  roman_daily_sametime: '/voices/roman_daily_sametime.mp3',
  coach_daily_done: '/voices/coach_daily_done.mp3',
  coach_daily_streak: '/voices/coach_daily_streak.mp3',
  coach_daily_great: '/voices/coach_daily_great.mp3',
  old_daily_paper: '/voices/old_daily_paper.mp3',
  old_daily_tomorrow: '/voices/old_daily_tomorrow.mp3',
  old_daily_everyday: '/voices/old_daily_everyday.mp3',
  coach_notbest_stands: '/voices/coach_notbest_stands.mp3',
  coach_notbest_okay: '/voices/coach_notbest_okay.mp3',
  coach_notbest_chase: '/voices/coach_notbest_chase.mp3',
  coach_notbest_breath: '/voices/coach_notbest_breath.mp3',
  coach_notbest_safe: '/voices/coach_notbest_safe.mp3',
  coach_notbest_practice: '/voices/coach_notbest_practice.mp3',
  coach_stash_five: '/voices/coach_stash_five.mp3',
  coach_stash_complete: '/voices/coach_stash_complete.mp3',
  coach_stash_bonus: '/voices/coach_stash_bonus.mp3',
  coach_stash_sparkle: '/voices/coach_stash_sparkle.mp3',
  // Buddy giggles
  buddy_giggle_1: '/voices/buddy_giggle_1.mp3',
  buddy_giggle_2: '/voices/buddy_giggle_2.mp3',
  buddy_giggle_3: '/voices/buddy_giggle_3.mp3',
} as const

export type VoiceLineId = keyof typeof VOICE_LINES

/**
 * Clips the voice channel may play: every catalog clip except the buddy giggles (those are a
 * synth sound effect now). All roman_* clips are the deeper Roman voice (en-US-BrianNeural,
 * rate -8%, pitch -6Hz); old_* clips are the old-timer heckler (en-AU-WilliamMultilingualNeural,
 * rate -20%, pitch -16Hz, rasp); coach lines are en-US-JennyNeural — see scripts/voice-manifest.json.
 */
export function isPlayableVoiceClip(id: string): boolean {
  return Object.prototype.hasOwnProperty.call(VOICE_LINES, id) && !id.startsWith('buddy_')
}

/** Coach clips worth prefetching (short, used for hints, badges, prizes and spark progress) */
export const WARM_COACH_CLIPS = [
  'nudge',
  'new_badge',
  'prize_time',
  'out_of_hearts',
  'tough_board',
  'spark_unlocked',
  'spark_1',
  'spark_2',
  'spark_3',
  'spark_4',
  'nice',
] as const

export type VoiceMood = 'excited' | 'happy' | 'neutral' | 'soft' | 'disappointed'

export type VoiceRole = 'coach' | 'roman' | 'oldtimer' | 'buddy'

export function roleForClip(id: string): VoiceRole {
  // 9.30-j fix: tip lines are tip_<tip>_<voice>_<name>; they used to all play as the coach
  if (id.startsWith('tip_')) {
    const v = id.split('_')[2]
    return v === 'roman' ? 'roman' : v === 'old' ? 'oldtimer' : 'coach'
  }
  if (id.startsWith('roman_')) return 'roman'
  if (id.startsWith('old_')) return 'oldtimer'
  if (id.startsWith('buddy_')) return 'buddy'
  return 'coach'
}

/**
 * Roman's playback speed for a mood rate (pitch preserved). Up to 9.30-g it was
 * min(0.94, max(0.82, rate * 0.88)); 9.30-h (Tony): about 10% quicker across the board,
 * so 0.902–1.034 (usually 1.034 for cheers, 1.026 for happy lines).
 */
export const ROMAN_RATE_SCALE = 0.968
export const ROMAN_RATE_MIN = 0.902
export const ROMAN_RATE_MAX = 1.034
export function romanPlaybackRate(moodRate: number): number {
  const r = Math.min(ROMAN_RATE_MAX, Math.max(ROMAN_RATE_MIN, moodRate * ROMAN_RATE_SCALE))
  return Math.round(r * 1000) / 1000
}

export function moodPlayback(mood: VoiceMood): { rate: number; volume: number } {
  switch (mood) {
    case 'excited':
      // Coach uplift — brighter & a touch faster
      return { rate: 1.08, volume: 0.96 }
    case 'happy':
      return { rate: 1.06, volume: 0.93 }
    case 'soft':
      return { rate: 1.0, volume: 0.86 }
    case 'disappointed':
      // Still gentle — not gloomy
      return { rate: 0.97, volume: 0.88 }
    default:
      return { rate: 1.03, volume: 0.9 }
  }
}
